#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           LDrive,        tmotorVex393HighSpeed_HBridge, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port10,          RDrive,        tmotorVex393HighSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//



void driveDistance(int inches, int power){
	nMotorEncoder[LDrive] = 0;

	int tickGoal = (35*inches);

	while( abs(nMotorEncoder[LDrive]) < tickGoal) {

		motor[LDrive] = 60;
		motor[RDrive] = 60;

	}

	motor[LDrive] = 0;
	motor[RDrive] = 0;

}

void turn (int direction) {
	motor[LDrive] = 60;
	motor[RDrive] = -60;
}

task main()
{
	while (1) {
		driveDistance(12, 60);
		wait1Msec (500);
		turn(1);
		wait1Msec(1650);

	}
}
